# Shell variables
# Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/punisher.jpg"

# Special
background='#090404'
foreground='#c1c0c0'
cursor='#c1c0c0'

# Colors
color0='#090404'
color1='#475666'
color2='#6E6A6A'
color3='#9A4443'
color4='#9F837C'
color5='#A09D9C'
color6='#CDB0A9'
color7='#c1c0c0'
color8='#665353'
color9='#475666'
color10='#6E6A6A'
color11='#9A4443'
color12='#9F837C'
color13='#A09D9C'
color14='#CDB0A9'
color15='#c1c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
