# Shell variables
# Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/inouske.jpg"

# Special
background='#1a1b1e'
foreground='#c5c6c6'
cursor='#c5c6c6'

# Colors
color0='#1a1b1e'
color1='#5691A5'
color2='#77BED8'
color3='#74BEDE'
color4='#76C1DD'
color5='#75C2E0'
color6='#BDC1B0'
color7='#c5c6c6'
color8='#606075'
color9='#5691A5'
color10='#77BED8'
color11='#74BEDE'
color12='#76C1DD'
color13='#75C2E0'
color14='#BDC1B0'
color15='#c5c6c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
