# Shell variables
# Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/killua.jpg"

# Special
background='#1b1e2f'
foreground='#c6c6cb'
cursor='#c6c6cb'

# Colors
color0='#1b1e2f'
color1='#837DB4'
color2='#1E8FB9'
color3='#2590B8'
color4='#5BA0BC'
color5='#9EAFBD'
color6='#D5D2D6'
color7='#c6c6cb'
color8='#65687b'
color9='#837DB4'
color10='#1E8FB9'
color11='#2590B8'
color12='#5BA0BC'
color13='#9EAFBD'
color14='#D5D2D6'
color15='#c6c6cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
