--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/inouske.jpg"

-- Special
background="#1a1b1e"
foreground="#c5c6c6"
cursor="#c5c6c6"

-- Colors
color0="#1a1b1e"
color1="#5691A5"
color2="#77BED8"
color3="#74BEDE"
color4="#76C1DD"
color5="#75C2E0"
color6="#BDC1B0"
color7="#c5c6c6"
color8="#606075"
color9="#5691A5"
color10="#77BED8"
color11="#74BEDE"
color12="#76C1DD"
color13="#75C2E0"
color14="#BDC1B0"
color15="#c5c6c6"
