[colors.primary]
background = "#1a1b1e"
foreground = "#c5c6c6"

[colors.cursor]
text = "#1a1b1e"
cursor = "#c5c6c6"

[colors.vi_mode_cursor]
text = "#1a1b1e"
cursor = "#c5c6c6"

[colors.search.matches]
foreground = "#1a1b1e"
background = "#c5c6c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606075"
background = "#c5c6c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1a1b1e"
red = "#5691A5"
green = "#77BED8"
yellow = "#74BEDE"
blue = "#76C1DD"
magenta = "#75C2E0"
cyan = "#BDC1B0"
white = "#c5c6c6"

[colors.bright]
black = "#606075"
red = "#5691A5"
green = "#77BED8"
yellow = "#74BEDE"
blue = "#76C1DD"
magenta = "#75C2E0"
cyan = "#BDC1B0"
white = "#c5c6c6"

[colors.dim]
black = "#c5c6c6"
red = "#5691A5"
green = "#75C2E0"
yellow = "#74BEDE"
blue = "#76C1DD"
magenta = "#77BED8"
cyan = "#BDC1B0"
white = "#606075"

