[colors]
background = '#1a1b1e8e'
black = '#1a1b1e'
blue = '#5691A5'
cursor = '#c5c6c6'
cyan = '#77BED8'
foreground = '#c5c6c6'
green = '#74BEDE'
magenta = '#76C1DD'
red = '#75C2E0'
tabs = '#c5c6c6'
tabs-active = '#BDC1B0'
white = '#c5c6c6'
yellow = '#c5c6c6'
dim-black = '#1a1b1e8e'
dim-blue = '#5691A58e'
dim-cyan = '#77BED88e'
dim-foreground = '#c5c6c68e'
dim-green = '#74BEDE8e'
dim-magenta = '#76C1DD8e'
dim-red = '#75C2E08e'
dim-white = '#BDC1B08e'
dim-yellow = '#c5c6c68e'
light-black = '#5691A5'
light-blue = '#77BED8'
light-cyan = '#74BEDE'
light-foreground = '#76C1DD'
light-green = '#75C2E0'
light-magenta = '#BDC1B0'
light-red = '#c5c6c6'
light-white = '#5691A5'
light-yellow = '#77BED8'
