# Shell variables
# Generated by 'wal'
wallpaper="/home/dark/arch-config/wallpapers/L.jpg"

# Special
background='#101312'
foreground='#c3c4c3'
cursor='#c3c4c3'

# Colors
color0='#101312'
color1='#596565'
color2='#77807E'
color3='#75888B'
color4='#9DA5A2'
color5='#BBC5C2'
color6='#DCDCD4'
color7='#c3c4c3'
color8='#596e64'
color9='#596565'
color10='#77807E'
color11='#75888B'
color12='#9DA5A2'
color13='#BBC5C2'
color14='#DCDCD4'
color15='#c3c4c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
